# Generated by Django 3.2.12 on 2022-03-17 04:36

import Red_Social.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Red_Social', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=Red_Social.models.user_directory_path)),
            ],
        ),
        migrations.AddField(
            model_name='socialpost',
            name='image',
            field=models.ManyToManyField(blank=True, to='Red_Social.Image'),
        ),
    ]
